//
//  ConstantData.swift
//  Guide
//
//  Created by Александра Мельникова on 05.10.2021.
//

import Foundation

var users = [User(name: "Александр",
                  lastName: "Петров",
                  mobile: "909898789",
                  email: "mn@mail.ru",
                  login: "1",
                  password: "1",
                  id: 0,
                  clients: [Client(name: "Никита",
                                   lastName: "Орлов",
                                   mobile: "89167876543",
                                   email: "",
                                   id: 0),
                            Client(name: "Иван",
                                   lastName: "Кузнецов",
                                   mobile: "89167876543",
                                   email: "",
                                   id: 1),
                            Client(name: "Федор",
                                   lastName: "Седов",
                                   mobile: "89167876543",
                                   email: "",
                                   id: 2),
                            Client(name: "Алексей",
                                   lastName: "Никитин",
                                   mobile: "89167876543",
                                   email: "",
                                   id: 3)],
                  tasks: [Task(name: "Уточнить количество человек",
                               date: Date(),
                               condition: .during,
                               responsibleID: 0,
                               clientID: 0,
                               id: 0),
                          Task(name: "Выполнить заявку",
                               date: Date(),
                               condition: .during,
                               responsibleID: 0,
                               clientID: 0,
                               id: 1),
                          Task(name: "Предложить перенос даты",
                               date: Date(),
                               condition: .done,
                               responsibleID: 0,
                               clientID: 0,
                               id: 2),
                          Task(name: "Назначить ответственного",
                               date: Date(),
                               condition: .canceled,
                               responsibleID: 0,
                               clientID: 0,
                               id: 3)],
                  events: [Event(id: 0,
                                 clientID: 0,
                                 date: Date(),
                                 place: "Tobizina",
                                 numberOfPersons: 2,
                                 price: 10000.0,
                                 comment: "Все прошло хорошо, клиент адекватный. Приехал вовремя",
                                 condition: .during),
                           Event(id: 1,
                                 clientID: 0,
                                 date: Date(),
                                 place: "Tobizina",
                                 numberOfPersons: 2,
                                 price: 6000.0,
                                 comment: "Все прошло хорошо, клиент адекватный. Приехал вовремя",
                                 condition: .done)])]

var currentUser = users[userID]
var userID = Int(DataManager.shared.loadUserID())

